# Generated by Django 6.0.6 on 2026-06-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('friend', 'Friend'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='students.student')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-entry_time'],
            },
        ),
    ]
